FROM node:16 AS build

WORKDIR /app

RUN git clone https://github.com/atx77/diplomski_frontend.git .

RUN npm install --legacy-peer-deps

RUN npm run build --prod

FROM nginx:stable-alpine

COPY --from=build /app/dist/webshop-ntpws /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
